NotafacilAPI\Image\Entity\Image:
    name: NotafacilAPI\Image\Entity\Image
    type: entity
    table: image
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        thumbPath:
            type: string
            nullable: false
            length: 256
            column: thumb_path
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        ctime:
            type: datetime
            nullable: false
        utime:
            type: datetime
            nullable: true
    manyToOne:
        user:
            targetEntity: NotafacilAPI\Image\Entity\User
            joinColumn:
                onDelete: SET NULL
            cascade: [ persist ]
    lifecycleCallbacks: {  }
